// Generated by CoffeeScript 1.6.3
var HomePageView, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

module.exports = HomePageView = (function(_super) {
  __extends(HomePageView, _super);

  function HomePageView() {
    _ref = HomePageView.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  HomePageView.prototype.template = require('./templates/page');

  HomePageView.prototype.initialize = function() {};

  HomePageView.prototype.render = function() {
    this.$el.html(this.template());
    return this;
  };

  return HomePageView;

})(Backbone.View);
